# Generated by Django 2.2.3 on 2019-08-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0003_tb_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=225)),
                ('e_salary', models.CharField(max_length=225)),
                ('e_experience', models.CharField(max_length=225)),
                ('e_profile', models.CharField(max_length=225)),
                ('e_detail', models.CharField(max_length=225)),
            ],
        ),
    ]
