# Generated by Django 2.2.3 on 2019-08-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0005_auto_20190826_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='e_id',
        ),
    ]
