# Generated by Django 2.2.3 on 2019-08-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0006_remove_emp_e_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp',
            new_name='emp_model',
        ),
    ]
